theme = "dark_plus"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
